name: Unused Code & Dependency Checker

on:
  schedule:
    - cron: '0 0 * * 2' # Every Tuesday at midnight
  workflow_dispatch:

jobs:
  check-unused:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Run Knip
        run: pnpm run --silent knip || true
